name: Run Application

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Set environment variables
      run: |
        echo "DEBUG=True" >> $GITHUB_ENV
        echo "DATABASE_URL=postgres://user:password@localhost:5432/mydatabase" >> $GITHUB_ENV
        echo "SECRET_KEY=your_secret_key" >> $GITHUB_ENV

    - name: Run database migrations
      run: python manage.py migrate

    - name: Start the application
      run: python manage.py runserver
